# Generated by Django 4.1.4 on 2023-01-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viaggi',
            options={'ordering': ['Data']},
        ),
    ]
