# Generated by Django 4.1.4 on 2023-01-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_viaggi_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViaggiDaFare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titolo', models.CharField(max_length=64)),
                ('Data', models.DateField()),
                ('Attivita', models.CharField(max_length=2000)),
                ('Luogo', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['Data'],
            },
        ),
        migrations.RenameModel(
            old_name='Viaggi',
            new_name='ViaggiFatti',
        ),
    ]
