# Generated by Django 4.1.4 on 2023-01-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_viaggidafare_attivita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaggifatti',
            name='campoRicerca',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
