# Generated by Django 4.1.4 on 2023-02-02 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0007_viaggifatti_camporicerca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaggifatti',
            name='campoRicerca',
        ),
        migrations.AddField(
            model_name='viaggidafare',
            name='Autore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='viaggifatti',
            name='Autore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
