# Generated by Django 4.1.5 on 2023-02-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_viaggifatti_camporicerca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaggifatti',
            name='campoRicerca',
        ),
    ]
